---
- name: Install on suse
  when: ansible_os_family | lower == "suse"
  include_tasks: zypp.yaml

- name: Install everywhere else
  when: not ansible_os_family | lower == "suse"
  block:
  - name: Gather package facts
    ansible.builtin.package_facts:
      manager: auto
      strategy: first

  - name: Install using apt
    when: "'apt' in ansible_facts.packages"
    include_tasks: apt.yaml

  - name: Install using yum
    when: "'yum' in ansible_facts.packages"
    include_tasks: yum.yaml

  - name: Install using apk
    when: "'apk-tools' in ansible_facts.packages"
    include_tasks: apk.yaml

  - name: Install using zypper not on Suse
    when: "'zypper' in ansible_facts.packages"
    include_tasks: zypp.yaml

- name: Open wazuh ports
  ansible.builtin.iptables:
    action: "insert"
    chain: "INPUT"
    protocol: "tcp"
    source: "{{ manager_ip }}"
    source_port: "{{ item }}"
    jump: "ACCEPT"
  loop: "{{ basic_ports }}"
    
- name: Open wazuh ports outbound
  ansible.builtin.iptables:
    action: "insert"
    chain: "OUTPUT"
    protocol: "tcp"
    destination: "{{ manager_ip }}"
    destination_port: "{{ item }}"
    jump: "ACCEPT"
  loop: "{{ basic_ports }}"
