- name: Disable Guest user
  ansible.windows.win_user:
    name: Guest
    account_disabled: true

- name: Disable Sticky Keys
  ansible.windows.win_regedit:
    name: "Flags"
    path: "HKCU:\\Control Panel\\Accessibility\\StickyKeys"
    data: "506"

- name: Disable all firewalls
  community.windows.win_firewall:
    state: "disabled"

- name: Back up and delete original firewall rules
  ansible.windows.win_shell: |
    netsh advfirewall export C:\backup.wfw
    Remove-NetFirewallRule -All

- name: Add ICMP rule
  community.windows.win_firewall_rule:
    action: "allow"
    description: "Allow icmp for network debugging"
    direction: "in"
    group: "Standard"
    name: "Allow ping"
    protocol: "icmpv4"

- name: Add localhost rule
  community.windows.win_firewall_rule:
    action: "allow"
    description: "Allow localhost into the network"
    direction: "in"
    group: "Standard"
    name: "Localhost in"
    remoteip: "127.0.0.0/8"

- name: Add RDP input rule
  community.windows.win_firewall_rule:
    action: "allow"
    description: "Allow RDP from team into network"
    direction: "in"
    group: "Blackout"
    name: "RDP from team"
    remoteip: '{{ team_ips | join(",") }}'
    localport: "3389"
    protocol: "tcp"

- name: Add RDP output rule
  community.windows.win_firewall_rule:
    action: "allow"
    description: "Allow RDP from team into network"
    direction: "out"
    group: "Blackout"
    name: "RDP to team"
    remoteip: '{{ team_ips | join(",") }}'
    localport: "3389"
    protocol: "tcp"

- name: Add winrm input rule
  community.windows.win_firewall_rule:
    action: "allow"
    description: "Allow winrm from team into network"
    direction: "in"
    group: "Standard"
    name: "winrm from team"
    remoteip: '{{ team_ips | join(",") }}'
    localport: "5985"
    protocol: "tcp"

- name: Add winrm output rule
  community.windows.win_firewall_rule:
    action: "allow"
    description: "Allow winrm from team into network"
    direction: "out"
    group: "Standard"
    name: "winrm to team"
    remoteip: '{{ team_ips | join(",") }}'
    localport: "5985"
    protocol: "tcp"

- name: Add internet connection rules
  community.windows.win_firewall_rule:
    action: "allow"
    description: "Allow http/s traffic out of network"
    direction: "out"
    group: "Internet"
    name: "Http/s traffic out"
    remoteport: "80,443"
    protocol: "tcp"

- name: Add DNS rules
  community.windows.win_firewall_rule:
    action: "allow"
    description: "Allow DNS traffic out of network"
    direction: "out"
    group: "Internet"
    name: "DNS traffic out"
    remoteport: "53"
    protocol: "udp"

- name: Add DC rules
  import_role: 
    name: DC

- name: Disable Internet rules
  community.windows.win_firewall_rule:
    group: "Internet"
    enabled: "false"

- name: Enable firewalls
  community.windows.win_firewall:
    state: "enabled"
    outbound_action: "block"

- name: Set up firewall logging
  ansible.windows.win_shell: Set-NetFirewallProfile -LogFileName %SystemRoot%\System32\LogFiles\Firewall\pfirewall.log

- name: Reboot
  ansible.windows.win_reboot:
