name: Install and Configure Auditd
hosts: linux
become: yes
strategy: free
tasks:
  - name: Enable internet access
    ansible.builtin.script: enable_internet.sh

  - name: Install Auditd
    block:
      - name: Install package auditd
        ansible.builtin.package:
          name: "auditd"
          state: "present"
    rescue:
      - name: Install package audit
        ansible.builtin.package:
          name: "audit"
          state: "present"
  
  - name: Disable internet access
    ansible.builtin.script: enable_internet.sh

  - name: Install custom rules
    ansible.builtin.copy:
      src: "audit.rules"
      dest: "/etc/audit/rules.d/"

  - name: Restart Auditd
    ansible.builtin.service:
      name: "auditd"
      state: "restarted"
