- name: Disable ruleset
  ansible.builtin.replace:
    regexp: "</ruleset>"
    path: "/var/ossec/etc/ossec.conf"
    replace:  "  <decoder_exclude>ruleset/decoders/0140-kernel_decoders.xml</decoder_exclude>\n    <decoder_exclude>ruleset/decoders/0040-auditd_decoders.xml</decoder_exclude>\n  </ruleset>"

- name: Delete decoder files (kernel)
  ansible.builtin.file:
    state: "absent"
    path: "/var/ossec/ruleset/decoders/0140-kernel_decoders.xml"

- name: Delete decoder files (auditd)
  ansible.builtin.file:
    state: "absent"
    path: "/var/ossec/ruleset/decoders/0040-auditd_decoders.xml"

- name: Place custom decoders (kernel)
  ansible.builtin.copy:
    dest: "/var/ossec/etc/decoders/"
    src: "0140-kernel_decoders.xml"

- name: Place custom decoders (auditd)
  ansible.builtin.copy:
    dest: "/var/ossec/etc/decoders/"
    src: "0040-auditd_decoders.xml"

- name: Place custom rules (iptables)
  ansible.builtin.copy:
    dest: "/var/ossec/etc/rules"
    src: "iptables-rules.xml"

- name: Place custom rules (auditd)
  ansible.builtin.copy:
    dest: "/var/ossec/etc/rules"
    src: "custom-auditd-rules.xml"

- name: Restart wazuh manager
  ansible.builtin.service:
    name: "wazuh-manager"
    state: "restarted"
