# Load default and service rules on Linux using iptables

- name: Flush current INPUT/OUTPUT Rules
  ansible.builtin.iptables:
    chain: "{{ item }}"
    flush: yes
  with_items: ['INPUT', 'OUTPUT']

- name: Add invalid packet rule
  ansible.builtin.iptables:
    chain: "{{ item }}"
    ctstate: ["INVALID"]
    jump: "DROP"
  with_items: ['INPUT', 'OUTPUT']

- name: Add localhost INPUT rule
  ansible.builtin.iptables:
    chain: "INPUT"
    source: "127.0.0.0/8"
    jump: "ACCEPT"

- name: Add localhost OUTPUT rule
  ansible.builtin.iptables:
    chain: "OUTPUT"
    destination: "127.0.0.0/8"
    jump: "ACCEPT"

- name: Add ICMP INPUT rule
  ansible.builtin.iptables:
    chain: "INPUT"
    protocol: "icmp"
    jump: "ACCEPT"

- name: Add ICMP OUTPUT rule
  ansible.builtin.iptables:
    chain: "OUTPUT"
    protocol: "icmp"
    jump: "ACCEPT"

- name: Add dns INPUT rule
  ansible.builtin.iptables:
    chain: "INPUT"
    protocol: "udp"
    source_port: "53"
    ctstate: ["ESTABLISHED"]
    jump: "ACCEPT"
  
- name: Add dns OUTPUT rule
  ansible.builtin.iptables:
    chain: "OUTPUT"
    protocol: "udp"
    destination_port: "53"
    jump: "ACCEPT"

- name: Add required INPUT rules
  ansible.builtin.iptables:
    chain: "INPUT"
    destination_port: "{{ item }}"
    jump: "ACCEPT"
    protocol: "tcp"
  loop: "{{ required_ports }}"

- name: Add required OUTPUT rules
  ansible.builtin.iptables:
    chain: "OUTPUT"
    source_port: "{{ item }}"
    ctstate: ["ESTABLISHED"]
    protocol: "tcp"
    jump: "ACCEPT"
  loop: "{{ required_ports }}"

- name: Add dropped INPUT LOG rule
  ansible.builtin.iptables:
    chain: "INPUT"
    jump: "LOG"
    log_prefix: "[DROPPED_INPUT] "

- name: Add dropped OUTPUT LOG rule
  ansible.builtin.iptables:
    chain: "OUTPUT"
    jump: "LOG"
    log_prefix: "[DROPPED_OUTPUT] "

- name: Add default drop rule
  ansible.builtin.iptables:
    chain: "{{ item }}"
    jump: "DROP"
  with_items: ['INPUT', 'OUTPUT']

- name: Save custom rules
  community.general.iptables_state:
    state: "saved"
    path: "/root/{{ inventory_hostname }}.rules"

- name: Grab custom rules
  ansible.builtin.fetch:
    flat: true
    src: "/root/{{ inventory_hostname }}.rules"
    dest: "roles/restore_rules/files/"
