- name: Install on Linux machines
  hosts: linux,!manager
  become: yes
  roles:
    - linux_agent
  tags:
    - install

- name: Install on Windows machines
  hosts: windows
  become: yes
  become_method: runas
  become_user: Administrator
  roles:
    - win_agent
  tags:
    - install

- name: Install on Solaris machines
  hosts: solaris
  become: yes
  roles:
    - solaris_agent
  tags:
    - install

- name: Install on BSD machines
  hosts: bsd
  become: yes
  roles:
    - bsd_agent
  tags:
    - install

    # - name: Install auditd
    #   import_playbook: ../auditd/auditd.yaml
    #   tags:
    #     - install

- name: Install the manager
  hosts: manager
  become: yes
  roles:
    - manager
  tags:
    - manager

- name: uninstall the wazuh agent
  hosts: linux,bsd,!manager
  become: yes
  roles:
    - linux_uninstall
  tags:
    - uninstall
